namespace: digital-assets
# Configmap #
configmap:
  name: experience-retail-kyc
  enabled: true
  data:
    application-pt.properties: |
      server.port=8091
      server.servlet.context-path=/digital-assets/onboarding
      spring.application.name=digital-assets-onboarding
      spring.threads.virtual.enabled=true

      # Database Configurations
      spring.datasource.url=jdbc:postgresql://localhost:5432/digital_assets_onboarding_local
      spring.datasource.username=postgres
      spring.datasource.password=
      spring.datasource.hikari.schema=${spring.jpa.properties.hibernate.default_schema}
      spring.jpa.properties.hibernate.default_schema=digital_assets_onboarding
      spring.jpa.properties.hibernate.ddl-auto=none
      spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

      # Actuator Configurations
      management.endpoints.web.exposure.include=*
      management.endpoint.health.show-details=always
      management.endpoints.web.base-path=/
      management.endpoints.web.path-mapping.health=health-check
      management.endpoint.health.probes.enabled=true
      management.endpoint.health.group.readiness.include=db
      management.info.env.enabled=true
      management.endpoint.prometheus.enabled=false

      # Batch configuration
      batch.initial-delay.minutes=2
      batch.interval.minutes=240
      batch.shedlock-at-least=PT5M
      batch.shedlock-at-most=PT10M
      batch.enabled=false

      # Observability configurations
      observability.correlationIdHeader=x-correlation-id
      observability.tracerName=digital-assets-onboarding

      # Swagger Configuration
      springdoc.swagger-ui.path=/swagger-ui.html

      # Application Specific Configuration
      digital-assets-onboarding.activityLog.db-logging.enable=true

      # Middleware properties
      digital-assets-onboarding.client.middleware.updateCifUrl=http://localhost:9093/middleware/updateCif

      # NotificationService properties
      digital-assets-onboarding.client.notificationservice.notificationUrl=http://localhost:8096/digital-assets/notifications/api/v1/customer/{cif}

      # ProductEligibility properties
      digital-assets-onboarding.client.producteligibility.eligibilityUrl=http://localhost:8095/product-eligibility/api/v1/customer/{cif}

      # Retry Config
      digital-assets-onboarding.downstream.api.retry.max-attempts=3
      digital-assets-onboarding.downstream.api.retry.max-delay-ms=3000

    logback-spring.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration>
          <property file="config/application-pt.properties"/>

          <conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter"/>
          <conversionRule conversionWord="wex" converterClass="org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter"/>
          <conversionRule conversionWord="wEx" converterClass="org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter"/>

          <springProfile name="pt">
              <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
                  <layout class="ch.qos.logback.classic.PatternLayout">
                      <pattern>%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n</pattern>
                  </layout>
              </appender>

              <logger name="org.springframework" level="INFO"/>
              <logger name="digital-assets-onboarding" level="DEBUG"/>

              <root level="INFO">
                  <appender-ref ref="Console"/>
              </root>
          </springProfile>
      </configuration>
# Deployment #
deployments:
  - name: experience-retail-kyc
    namespace: digital-assets
    replicaCount: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 6
      targetCPUUtilizationPercentage: 75
    containerName: experience-retail-kyc-container
    image:
      registry: "<YOUR_IMAGE_REGISTRY>"
      repository: "<YOUR_IMAGE_REPOSITORY>"
      tag: "<YOUR_IMAGE_TAG>"
    containerPort: 8091
    configMapRef:
      name: experience-retail-kyc
    secretRef:
      name: kyc-retail-secrets
    env:
      - name: OTEL_SERVICE_NAME
        value: "digital-assets-onboarding"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "<YOUR_OTEL_ENDPOINT>"
      - name: AWS_REGION
        value: "me-central-1"
      - name: TZ
        value: "Asia/Dubai"
      - name: SPRING_PROFILES_ACTIVE
        value: "pt"
    resources:
      limits:
        memory: "2000Mi"
      requests:
        cpu: "512m"
        memory: "2000Mi"
    livenessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/liveness
        port: 8091
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/readiness
        port: 8091
      initialDelaySeconds: 30
      periodSeconds: 10
    nodeSelector:
      environment: pt
    volumes:
      - name: app-properties
        configMap:
          name: experience-retail-kyc
    volumeMounts:
      - name: app-properties
        mountPath: /usr/app/config
        items:
          - key: application-pt.properties
            path: application-pt.properties
          - key: logback-spring.xml
            path: logback-spring.xml
# Service #
service:
  name: experience-retail-kyc-service
  selector:
    app: experience-retail-kyc
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
# External Secrets #
externalsecrets:
  enabled: true
  name: digital-assets-external-secrets
  secretStoreRef: aws-secrets-store
  target:
    name: kyc-retail-secrets
  data:
    - secretKey: spring.datasource.url
      remoteRef:
        key: /digital-assets/onboarding
        property: spring.datasource.url
    - secretKey: spring.datasource.username
      remoteRef:
        key: /digital-assets/onboarding
        property: spring.datasource.username
    - secretKey: spring.datasource.password
      remoteRef:
        key: /digital-assets/onboarding
        property: spring.datasource.password
    - secretKey: spring.redis.host
      remoteRef:
        key: /digital-assets/onboarding
        property: spring.redis.host
    - secretKey: spring.redis.port
      remoteRef:
        key: /digital-assets/onboarding
        property: spring.redis.port
    - secretKey: spring.redis.username
      remoteRef:
        key: /digital-assets/onboarding
        property: spring.redis.username
    - secretKey: spring.redis.password
      remoteRef:
        key: /digital-assets/onboarding
        property: spring.redis.password
