Error: template: helmonechart/templates/deployment.yaml:45:32: executing "helmonechart/templates/deployment.yaml" at <$deployment.image.registry>: nil pointer evaluating interface {}.registry
Use --debug flag to render out invalid YAML
