namespace: digital-assets
# Configmap #
configmap:
  name: digital-assets-onboarding-configmap
  enabled: true
  data:
    application-pt.properties: |
      server.port=8091
      server.servlet.context-path=/digital-assets/onboarding
      spring.application.name=digital-assets-onboarding
      spring.threads.virtual.enabled=true

      # Database Configurations
      spring.datasource.url=${SPRING_DATASOURCE_URL}
      spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
      spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
      spring.jpa.properties.hibernate.default_schema=${SPRING_JPA_HIBERNATE_SCHEMA}
      spring.jpa.properties.hibernate.ddl-auto=none
      spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

      # Actuator Configurations
      management.endpoints.web.exposure.include=*
      management.endpoint.health.show-details=always
      management.endpoints.web.base-path=/
      management.endpoints.web.path-mapping.health=health-check
      management.endpoint.health.probes.enabled=true
      management.endpoint.health.group.readiness.include=db
      management.info.env.enabled=true
      management.endpoint.prometheus.enabled=false

      # Batch configuration
      batch.initial-delay.minutes=2
      batch.interval.minutes=240
      batch.shedlock-at-least=PT5M
      batch.shedlock-at-most=PT10M
      batch.enabled=false

      # Observability configurations
      observability.correlationIdHeader=x-correlation-id
      observability.tracerName=digital-assets-onboarding

      # Swagger Configuration
      springdoc.swagger-ui.path=/swagger-ui.html

      # Application Specific Configuration
      digital-assets-onboarding.activityLog.db-logging.enable=true

      # Middleware properties
      digital-assets-onboarding.client.middleware.updateCifUrl=${MIDDLEWARE_UPDATE_CIF_URL}

      # NotificationService properties
      digital-assets-onboarding.client.notificationservice.notificationUrl=${NOTIFICATION_SERVICE_URL}

      # ProductEligibility properties
      digital-assets-onboarding.client.producteligibility.eligibilityUrl=${PRODUCT_ELIGIBILITY_URL}

      # Retry Config
      digital-assets-onboarding.downstream.api.retry.max-attempts=${DOWNSTREAM_API_RETRY_MAX_ATTEMPTS}
      digital-assets-onboarding.downstream.api.retry.max-delay-ms=${DOWNSTREAM_API_RETRY_MAX_DELAY_MS}

    logback-spring.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration>
          <property file="config/application-pt.properties"/>

          <conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter"/>
          <conversionRule conversionWord="wex" converterClass="org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter"/>
          <conversionRule conversionWord="wEx" converterClass="org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter"/>

          <springProfile name="pt">
              <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
                  <layout class="ch.qos.logback.classic.PatternLayout">
                      <pattern>%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n</pattern>
                  </layout>
              </appender>

              <logger name="org.springframework" level="INFO"/>
              <logger name="digital-assets-onboarding" level="DEBUG"/>

              <root level="INFO">
                  <appender-ref ref="Console"/>
              </root>
          </springProfile>
      </configuration>
# External Secrets #
externalsecrets:
  enabled: true
  name: digital-assets-onboarding-external-secrets
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: digital-assets-onboarding-secrets
    creationPolicy: Owner
  data:
    # Database Secrets
    - secretKey: spring.datasource.url
      remoteRef:
        key: digital_wallet_secret
        property: spring.datasource.url
    - secretKey: spring.datasource.username
      remoteRef:
        key: digital_wallet_secret
        property: spring.datasource.username
    - secretKey: spring.datasource.password
      remoteRef:
        key: digital_wallet_secret
        property: spring.datasource.password
    - secretKey: spring.jpa.properties.hibernate.default_schema
      remoteRef:
        key: digital_wallet_secret
        property: spring.jpa.properties.hibernate.default_schema

    # Application Secrets
    - secretKey: digital-assets-onboarding.client.middleware.updateCifUrl
      remoteRef:
        key: digital_asset_dev
        property: digital-assets-onboarding.client.middleware.updateCifUrl
    - secretKey: digital-assets-onboarding.client.notificationservice.notificationUrl
      remoteRef:
        key: digital_asset_dev
        property: digital-assets-onboarding.client.notificationservice.notificationUrl
    - secretKey: digital-assets-onboarding.client.producteligibility.eligibilityUrl
      remoteRef:
        key: digital_asset_dev
        property: digital-assets-onboarding.client.producteligibility.eligibilityUrl
    - secretKey: digital-assets-onboarding.downstream.api.retry.max-attempts
      remoteRef:
        key: digital_asset_dev
        property: digital-assets-onboarding.downstream.api.retry.max-attempts
    - secretKey: digital-assets-onboarding.downstream.api.retry.max-delay-ms
      remoteRef:
        key: digital_asset_dev
        property: digital-assets-onboarding.downstream.api.retry.max-delay-ms

# Deployment #
deployments:
  - name: digital-assets-onboarding-service
    namespace: digital-assets
    replicaCount: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 6
      targetCPUUtilizationPercentage: 75
    containerName: digital-assets-onboarding-container
    image:
      registry: "<YOUR_IMAGE_REGISTRY>"
      repository: "<YOUR_IMAGE_REPOSITORY>"
      tag: "<YOUR_IMAGE_TAG>"
    containerPort: 8091
    configMapRef:
      name: digital-assets-onboarding-configmap
    env:
      # Database Secrets from External Secrets
      - name: SPRING_DATASOURCE_URL
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: spring.datasource.url
      - name: SPRING_DATASOURCE_USERNAME
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: spring.datasource.username
      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: spring.datasource.password
      - name: SPRING_JPA_HIBERNATE_SCHEMA
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: spring.jpa.properties.hibernate.default_schema

      # Application Secrets from External Secrets
      - name: MIDDLEWARE_UPDATE_CIF_URL
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: digital-assets-onboarding.client.middleware.updateCifUrl
      - name: NOTIFICATION_SERVICE_URL
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: digital-assets-onboarding.client.notificationservice.notificationUrl
      - name: PRODUCT_ELIGIBILITY_URL
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: digital-assets-onboarding.client.producteligibility.eligibilityUrl
      - name: DOWNSTREAM_API_RETRY_MAX_ATTEMPTS
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: digital-assets-onboarding.downstream.api.retry.max-attempts
      - name: DOWNSTREAM_API_RETRY_MAX_DELAY_MS
        valueFrom:
          secretKeyRef:
            name: digital-assets-onboarding-secrets
            key: digital-assets-onboarding.downstream.api.retry.max-delay-ms

      - name: TZ
        value: "Asia/Dubai"
      - name: SPRING_PROFILES_ACTIVE
        value: "pt"
    resources:
      limits:
        memory: "2000Mi"
      requests:
        cpu: "512m"
        memory: "2000Mi"
    livenessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/liveness
        port: 8091
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/readiness
        port: 8091
      initialDelaySeconds: 30
      periodSeconds: 10
    nodeSelector:
      environment: pt
    volumes:
      - name: app-properties
        configMap:
          name: digital-assets-onboarding-configmap
    volumeMounts:
      - name: app-properties
        mountPath: /usr/app/config
        items:
          - key: application-pt.properties
            path: application-pt.properties
          - key: logback-spring.xml
            path: logback-spring.xml
# Internal Service #
service:
  name: digital-assets-onboarding-service
  selector:
    app: digital-assets-onboarding-service
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
# External Service #
externalService:
  enabled: true
  name: digital-assets-onboarding-external-service
  selector:
    app: digital-assets-onboarding-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8091
  type: LoadBalancer
# PDB (Pod Disruption Budget) #
pdb:
  enabled: true
  name: digital-assets-onboarding-pdb
  namespace: digital-assets
  minAvailable: 2
  labels:
    app: digital-assets-onboarding-service
  selector:
    matchLabels:
      app: digital-assets-onboarding-service
