namespace: digital-assets
# Configmap #
configmap:
  name: digital-assets-onboarding-configmap
  enabled: true
  data:
    application-pt.properties: |
      server.port=8091
      server.servlet.context-path=/digital-assets/onboarding
      spring.application.name=digital-assets-onboarding
      spring.threads.virtual.enabled=true

      # Database Configurations
      spring.datasource.url=file:/etc/secrets/spring.datasource.url
      spring.datasource.username=file:/etc/secrets/spring.datasource.username
      spring.datasource.password=file:/etc/secrets/spring.datasource.password
      spring.jpa.properties.hibernate.default_schema=file:/etc/secrets/spring.jpa.properties.hibernate.default_schema
      spring.jpa.properties.hibernate.ddl-auto=none
      spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

      # Actuator Configurations
      management.endpoints.web.exposure.include=*
      management.endpoint.health.show-details=always
      management.endpoints.web.base-path=/
      management.endpoints.web.path-mapping.health=health-check
      management.endpoint.health.probes.enabled=true
      management.endpoint.health.group.readiness.include=db
      management.info.env.enabled=true
      management.endpoint.prometheus.enabled=false

      # Batch configuration
      batch.initial-delay.minutes=2
      batch.interval.minutes=240
      batch.shedlock-at-least=PT5M
      batch.shedlock-at-most=PT10M
      batch.enabled=false

      # Observability configurations
      observability.correlationIdHeader=x-correlation-id
      observability.tracerName=digital-assets-onboarding

      # Swagger Configuration
      springdoc.swagger-ui.path=/swagger-ui.html

      # Application Specific Configuration
      digital-assets-onboarding.activityLog.db-logging.enable=true

      # Middleware properties
      digital-assets-onboarding.client.middleware.updateCifUrl=file:/etc/secrets/middleware.updateCifUrl

      # NotificationService properties
      digital-assets-onboarding.client.notificationservice.notificationUrl=file:/etc/secrets/notificationservice.notificationUrl

      # ProductEligibility properties
      digital-assets-onboarding.client.producteligibility.eligibilityUrl=file:/etc/secrets/producteligibility.eligibilityUrl

      # Retry Config
      digital-assets-onboarding.downstream.api.retry.max-attempts=file:/etc/secrets/retry.max-attempts
      digital-assets-onboarding.downstream.api.retry.max-delay-ms=file:/etc/secrets/retry.max-delay-ms

    logback-spring.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration>
          <property file="config/application-pt.properties"/>

          <conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter"/>
          <conversionRule conversionWord="wex" converterClass="org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter"/>
          <conversionRule conversionWord="wEx" converterClass="org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter"/>

          <springProfile name="pt">
              <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
                  <layout class="ch.qos.logback.classic.PatternLayout">
                      <pattern>%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n</pattern>
                  </layout>
              </appender>

              <logger name="org.springframework" level="INFO"/>
              <logger name="digital-assets-onboarding" level="DEBUG"/>

              <root level="INFO">
                  <appender-ref ref="Console"/>
              </root>
          </springProfile>
      </configuration>
# External Secrets #
externalsecrets:
  enabled: true
  name: digital-assets-onboarding-external-secrets
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: digital-assets-onboarding-secrets
    creationPolicy: Owner
  data:
    # Database Secrets
    - secretKey: spring.datasource.url
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: spring.datasource.url
    - secretKey: spring.datasource.username
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: spring.datasource.username
    - secretKey: spring.datasource.password
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: spring.datasource.password
    - secretKey: spring.jpa.properties.hibernate.default_schema
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: spring.jpa.properties.hibernate.default_schema

    # Application Secrets
    - secretKey: middleware.updateCifUrl
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: middleware.updateCifUrl
    - secretKey: notificationservice.notificationUrl
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: notificationservice.notificationUrl
    - secretKey: producteligibility.eligibilityUrl
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: producteligibility.eligibilityUrl
    - secretKey: retry.max-attempts
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: retry.max-attempts
    - secretKey: retry.max-delay-ms
      remoteRef:
        key: digital_assets_onboarding_secrets
        property: retry.max-delay-ms

# Deployment #
deployments:
  - name: digital-assets-onboarding-service
    namespace: digital-assets
    replicaCount: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 6
      targetCPUUtilizationPercentage: 75
    containerName: digital-assets-onboarding-container
    image:
      registry: "625611776955.dkr.ecr.me-central-1.amazonaws.com"
      repository: "digital-asset-service"
      tag: "develop-ae8464b"
    containerPort: 8091
    configMapRef:
      name: digital-assets-onboarding-configmap
    volumes:
      - name: secret-volume
        secret:
          secretName: digital-assets-onboarding-secrets
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
        readOnly: true
    env:
      - name: TZ
        value: "Asia/Dubai"
      - name: SPRING_PROFILES_ACTIVE
        value: "pt"
    resources:
      limits:
        memory: "2000Mi"
      requests:
        cpu: "512m"
        memory: "2000Mi"
    livenessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/liveness
        port: 8091
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/readiness
        port: 8091
      initialDelaySeconds: 30
      periodSeconds: 10
    nodeSelector:      project: deh
# Service #
service:
  name: digital-assets-onboarding-service
  selector:
    app: digital-assets-onboarding-service
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
# External Service #
externalService:
  enabled: true
  name: digital-assets-onboarding-external-service
  selector:
    app: digital-assets-onboarding-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8091
  type: LoadBalancer
# PDB (Pod Disruption Budget) #
pdb:
  enabled: true
  name: digital-assets-onboarding-pdb
  namespace: digital-assets
  minAvailable: 2
  labels:
    app: digital-assets-onboarding-service
  selector:
    matchLabels:
      app: digital-assets-onboarding-service

/da-dev/digital-assets-onboarding
