namespace: digital-wallet
# Configmap #
configmap:
  name: digital-assets-onboarding-configmap
  enabled: true
  data:
    application-dev.properties: |
      server.port=8091
      server.servlet.context-path=/digital-assets/onboarding
      spring.application.name=digital-assets-onboarding
      spring.threads.virtual.enabled=true

      # Database Configurations
      spring.datasource.url=file:/etc/secrets/spring.datasource.url
      spring.datasource.username=file:/etc/secrets/spring.datasource.username
      spring.datasource.password=file:/etc/secrets/spring.datasource.password
      spring.jpa.properties.hibernate.default_schema=file:/etc/secrets/spring.jpa.properties.hibernate.default_schema
      spring.jpa.properties.hibernate.ddl-auto=none
      spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

      # Actuator Configurations
      management.endpoints.web.exposure.include=*
      management.endpoint.health.show-details=always
      management.endpoints.web.base-path=/
      management.endpoints.web.path-mapping.health=health-check
      management.endpoint.health.probes.enabled=true
      management.endpoint.health.group.readiness.include=db
      management.info.env.enabled=true
      management.endpoint.prometheus.enabled=false

      # Batch configuration
      batch.initial-delay.minutes=2
      batch.interval.minutes=240
      batch.shedlock-at-least=PT5M
      batch.shedlock-at-most=PT10M
      batch.enabled=false

      # Notifications Batch Configuration
      digital-assets-onboarding.notifications.batch.initial-delay.minutes=2
      digital-assets-onboarding.notifications.batch.interval.minutes=240
      digital-assets-onboarding.notifications.batch.shedlock-at-least=PT5M
      digital-assets-onboarding.notifications.batch.shedlock-at-most=PT10M
      digital-assets-onboarding.notifications.batch.enabled=false
      digital-assets-onboarding.notifications.batch.max-retry-attempts=3

      # Observability configurations
      observability.correlationIdHeader=x-correlation-id
      observability.tracerName=digital-assets-onboarding

      # Swagger Configuration
      springdoc.swagger-ui.path=/swagger-ui.html

      # Application Specific Configuration
      digital-assets-onboarding.activityLog.db-logging.enable=true

      # Middleware properties
      digital-assets-onboarding.client.middleware.updateCifUrl=http://localhost:9093/middleware/updateCif

      # NotificationService properties
      digital-assets-onboarding.client.notificationservice.notificationUrl=http://localhost:8096/digital-assets/notifications/api/v1/customer/{cif}

      # ProductEligibility properties
      digital-assets-onboarding.client.producteligibility.eligibilityUrl=http://localhost:8095/product-eligibility/api/v1/customer/{cif}

      # Retry Config
      digital-assets-onboarding.downstream.api.retry.max-attempts=3
      digital-assets-onboarding.downstream.api.retry.max-delay-ms=3000
# External Secrets #
externalsecrets:
  enabled: true
  name: digital-assets-onboarding-external-secrets
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: /da-dev/digital-assets-onboarding
    creationPolicy: Owner
  data:
    # Database Secrets
    - secretKey: spring.datasource.url
      remoteRef:
        key: /da-dev/digital-assets-onboarding
        property: spring.datasource.url
    - secretKey: spring.datasource.username
      remoteRef:
        key: /da-dev/digital-assets-onboarding
        property: spring.datasource.username
    - secretKey: spring.datasource.password
      remoteRef:
        key: /da-dev/digital-assets-onboarding
        property: spring.datasource.password
    - secretKey: spring.jpa.properties.hibernate.default_schema
      remoteRef:
        key: /da-dev/digital-assets-onboarding
        property: spring.jpa.properties.hibernate.default_schema
# Deployment #
deployments:
  - name: digital-assets-onboarding-service
    namespace: digital-wallet
    replicaCount: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 75
    containerName: digital-assets-onboarding-container
    image:
      registry: "625611776955.dkr.ecr.me-central-1.amazonaws.com"
      repository: "digital-asset-service"
      tag: "develop-ae8464b"
    containerPort: 8091
    configMapRef:
      name: digital-assets-onboarding-configmap
    volumes:
      - name: secret-volume
        secret:
          secretName: /da-dev/digital-assets-onboarding
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
        readOnly: true
    env:
      - name: TZ
        value: "Asia/Dubai"
      - name: SPRING_PROFILES_ACTIVE
        value: "dev"
    resources:
      limits:
        cpu: "256m"
        memory: "256Mi"
      requests:
        cpu: "256m"
        memory: "256Mi"
    livenessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/liveness
        port: 8091
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /digital-assets/onboarding/health-check/readiness
        port: 8091
      initialDelaySeconds: 30
      periodSeconds: 10
    nodeSelector:
      application_visa: "visa-epp"
      application_digital: "digital-assets"
      project: "da"
# Service #
service:
  name: digital-assets-onboarding-service
  selector:
    app: digital-assets-onboarding-service
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
# Istio Gateway #
gateway:
  enabled: true
  name: digital-assets-onboarding-gateway
  port:
    number: 443
    protocol: HTTPS
  tls:
    mode: SIMPLE
    cert: istio-digital-assets-certificate
  hosts:
    - "digitalasset-dev.rakbanktst.ae"
# Virtual Service #
virtualService:
  enabled: true
  name: retail-accounts-virtual-service
  namespace: digital-wallet
  hosts:
    - "digitalasset-dev.rakbanktst.ae"
  gateway: digital-assets-onboarding-gateway
  http:
    - uri: "/digital-assets"
      route:
        - host: digital-assets-onboarding-service
          subset: v1
          port: 8091
      retries:
        attempts: 3
        perTryTimeout: "10s"
        retryOn: "5xx,connect-failure"
destinationRule:
  enabled: true
  name: digital-assets-onboarding-destination-rule
  host: digital-assets-onboarding-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2


Release "digital-assets-onboarding-service" does not exist. Installing it now.
Error: Deployment.apps "digital-assets-onboarding-service" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string(nil), MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: empty selector is invalid for deployment
